# -*- coding: utf-8 -*-
"""train_unsloth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Blv4XtQ93Oh6A_Mea9ob0ZJUG_M-RdWj
"""

# --- CELL 1: Install Optimized Libraries ---
# 1. Fetch pre-compiled xformers wheel from PyTorch index (takes 5 seconds)
!pip install --no-deps xformers --index-url https://download.pytorch.org/whl/cu121

# 2. Install unsloth & dependencies without compiling
!pip install --no-deps "trl<0.9.0" peft accelerate bitsandbytes
!pip install "unsloth[kaggle] @ git+https://github.com/unslothai/unsloth.git"

# --- CELL 2: Load Model in 4-bit Precision ---
from unsloth import FastLanguageModel
import torch

max_seq_length = 2048
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen2.5-7B-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = None,
    load_in_4bit = True,
)

# --- CELL 3: Configure LoRA Parameter Efficient Adapters ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Rank
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0.0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

import os
for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.endswith(".jsonl") or file.endswith(".json"):
            print(os.path.join(root, file))

# --- CELL 4: Load Synthetic Dataset ---
from datasets import load_dataset
# Update dataset path to match your uploaded Kaggle dataset
dataset = load_dataset("json",
    data_files="/kaggle/input/datasets/ahmedsamy2003/train-data-jsonl/train_data.jsonl",
    split="train")

print(dataset[0].keys())

# --- CELL 5: Train Model with SFTTrainer ---
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

# 1. Define the chat template formatting function
def format_prompts(examples):
    # Unsloth/Hugging Face batch processing or single sample check
    if isinstance(examples["messages"][0], list):
        texts = [
            tokenizer.apply_chat_template(msg, tokenize=False, add_generation_prompt=False)
            for msg in examples["messages"]
        ]
    else:
        texts = [tokenizer.apply_chat_template(examples["messages"], tokenize=False, add_generation_prompt=False)]
    return texts

# 2. Initialize SFTTrainer
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    formatting_func = format_prompts,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

trainer_stats = trainer.train()

# Save light adapters (~150MB) directly
model.save_pretrained("qwen2.5_gym_coach_lora")
tokenizer.save_pretrained("qwen2.5_gym_coach_lora")

# Create zip file
shutil.make_archive("qwen2.5_gym_coach_lora", 'zip', "qwen2.5_gym_coach_lora")

print("[PASS] Saved and zipped adapters successfully without filling disk space.")

import os
import shutil
from IPython.display import FileLink

# Ensure working directory is /kaggle/working
os.chdir('/kaggle/working')

# 1. Zip the adapters directory if it isn't zipped yet
if not os.path.exists("qwen2.5_gym_coach_lora.zip"):
    shutil.make_archive("qwen2.5_gym_coach_lora", 'zip', "qwen2.5_gym_coach_lora")

# 2. Display a direct download link in the notebook output
FileLink(r'qwen2.5_gym_coach_lora.zip')

FastLanguageModel.for_inference(model)

test_queries = [
    "My lower back feels completely compressed during conventional deadlifts.",
    "My bench press has been stuck at 85kg for 4 weeks in a row.",
    "I'm at a hotel gym with only 15kg dumbbells. Give me a shoulder workout.",
    "Where should my elbows be positioned during a flat bench press?"
]

print("=== RUNNING INFERENCE BENCHMARK ===")
for q in test_queries:
    messages = [
        {"role": "system", "content": "You are an elite Gym Coach AI. You manage user programming, injuries, and progressive overload. You have access to tools: 'search_medical_db', 'search_exercise_catalog', 'generate_workout'. If an injury or plateau is present, output strict JSON tool calls. If direct form advice, output coaching text."},
        {"role": "user", "content": q}
    ]
    inputs = tokenizer.apply_chat_template(messages, tokenize=True,
        add_generation_prompt=True, return_tensors="pt").to("cuda")
    outputs = model.generate(input_ids=inputs, max_new_tokens=150,
        use_cache=True)
    decoded = tokenizer.batch_decode(outputs)
    print(f"\n[QUERY]:\n{q}\n[RESPONSE]:\n{decoded[0].split('<|im_start|>assistant')[-1]}")